### ISSUE TITLE
Add layer management

### ISSUE THREAD

**Issue by iOiurson** [mapcontrib/mapcontrib.next#14]
The basic functionality from MapContrib v1 is layer management.
We need to implement this to be able to have a somewhat functional app.

### Structure
Based on v1, each layer should have
- name
- type (overpass, osmose, csv, geojson...)
- description
- marker
- representationType (cluster or heatmap)
- isVisible
- sources

I feel these are not necessary:
- popup content (info could be displayed on the sidebar)
- min zoom level (this could be a general option, or even not an option at all)

### Sources
The sources (plural) is mainly to allow one layer to have multiple sources. This is interesting especially for Osmose, because this will allow to regroup similar osmose items under the same layer.
We could accept multiple sources only for osmose layers.
The sources field will hold either the overpass query, the osmose items, or the files' path.

### UX
We could have a layer edition right sidebar for creation/modification, and a quick left toolbar for toggle display and representation type.

**Comment by GuillaumeAmat** [comment]
I totally agree on that first step to be functional. And your proposition to implement multiple sources per layer is a great idea but I think we should push it further.

In your proposal you talk about specific layer types (overpass, files, etc.) _and_ multiple sources (and source types). It is confused IMHO.

What do you think about having:
* Layers
  * which handle name, description, visibility, representation type
* Sources
  * which have types, marker customization, visibility (too), content display (former popup content)

The _content display_ is really important to the theme creators, but the popup form is really annoying and has to be removed. Sidebars and modals are sufficient enough.

**Comment by GuillaumeAmat** [comment]
@iOiurson I will work on that today. Since I don't see any branch related to that issue, I assume there is no started work on your side. Is it correct?

My goal is to publish a first version of MapContrib Next very soon, with a minimal layer handling.

**Comment by iOiurson** [comment]
I confirm no work has been started on my side.

Be careful though, for the osmose basic functionality, i set the store so that it stores the entire leaflet layer. I do not think this is an optimal solution for store persistance, and was planning on giving it a deeper thought.

Maybe store just the osmose item (probably better for simplicity) and recreate the layer on each render if the item has changed (but need to check on perfs).

**Comment by iOiurson** [comment]
I was thinking about tackling this baby, so that we are able to read/write layers from the database with MC Next.

### Layers server-side
What should I expect from the server in terms of layer data ?
How is it structured ? 
What's the API ? (I have tried to read the `api` folder from MC, but I must admit it's a bit harsh...)
Is the server capable of handling sources ? (My guess is no)

### One thought about layers and sources.
In my opinion, layers should handle all about the type and representation (marker, color, ...), and sources should only be about the data sources (and consequently the leaflet-layer).
When I brought up the concept of sources, I had Osmose in mind and the fact that one could want to have all School items (Osmose items can be very similar) into one single layer, and all being represented by the same marker. This leads to having multiple sources for one layer.
The other case that could benefit from having multiple sources is external files. We can think of some person that has data of the same kind in different files, and that would make sense to import all the data into one single layer, represented by the same marker.

But I think that in the vast majority of cases, people shouldn't have multiple sources per layer. If they absolutely want to, ok, but a layer represents one kind of data, and has one style. If you want multiple styles, you probably have different kinds of data, and should have different layers too then.

This would lead to such structure, layers and sources being 2 different stores:

##### Layers
- id
- name
- type (overpass, osmose, csv, geojson..., one layer, one type)
- description
- marker
- representationType (cluster or heatmap)
- isVisible
- sources (array of sources id)

##### Sources
- id
- type
- origin (the Osmose item, the Overpass request, the file name,...)
- features

**Comment by GuillaumeAmat** [comment]
Great to hear! :)

I understand your point but I kind of feeling it weird to seperate the data type (in the layer) and the data ID (item/request in the source). Such hard bond should be avoided IMHO.

What about that kind of use case:
I'm concerned about the environment, so I create an MC theme to improve the OSM database about that.
I want to improve several things: trees, parks, etc.
So I would like to have a layer per category of things: one for trees, one for parks and so on.
In each layer, it might make sense to have multiple source types and customizations:

* an Overpass request to see the current data state in OSM
* some Osmose items to see what can be easily improved
* etc.

That way I can hide/show the layers/things I want to focus on (a main subject of contribution for today) and I also can see a visual difference between Overpass and Osmose data, making it easier to me to navigate and analyse.


In the end, I think we should remove constraints/bond as much as we can, without sacrifying the UX of casual users nor expert users.

What bout that?

* Put the data type in the source
* Handle a customization in the layer to apply to all the sources by default
* Handle a customization in the source to override the default **if** the user wants to make a difference

That way, all the users/use cases should be addressed don't you think?

**Comment by iOiurson** [comment]
Ok I get your point.

I still believe that sources should have nothing to do with visual customization (marker, isVisible, ...). Layers only should handle that.

Let's take the use case you provided.

The user creates a layer for OSM trees, and adds the corresponding Overpass request as source.
The user creates a layer for osmose trees, and adds the 3 existing Osmose ids as sources.
The user creates a layer for custom points (his personal feelings about missing trees for instance), using a local JSON for source.

The same thing happens for parks, trash bins.

The user now has 9 layers, connected to 15 sources (because 3 osmose sources each time).
For UX purposes, he needs to separate these 9 layers into 3.

For this case, **we can imagine that the user creates a meta layer**, which would be a group/layer of layers, with no sources, but all the display functionalities of layers: markers, isVisible, ... that would be the default styles for child layers if no style is defined.

Of course, the UX of such story would need to be well designed to make sure this stays comfortable to do. We can imagine a folder-like display of layers, that we could drag and drop.


I really have a bad feeling about mixing sources and layers in terms of display controls.
And about your concern of data types being in the layers, this could be a "fake" property of the layer, coming directly from the source just for user information purposes.

What do you think ?

**Comment by GuillaumeAmat** [comment]
I will work on that soon. Reassign it to me if it's ok for you @iOiurson

**Comment by GuillaumeAmat** [comment]
The repository moved to https://gitlab.com/mapcontrib/mapcontrib.next.
