### ISSUE TITLE
Change the default changeset

### ISSUE THREAD

**Issue by vinber** [mapcontrib/mapcontrib.next#16]
at least an OSM user link -> https://www.openstreetmap.org/user/MapContrib

**Comment by GuillaumeAmat** [comment]
Can you elaborate @vinber? I'm not sure to understand the point.

I already changed the changeset attributes two days ago. They are now the same as in MC.

**Comment by vinber** [comment]
i think there's two informations in the changeset :
- theme's link
- and a way to ask about MC (github issue or osm account)

**Comment by GuillaumeAmat** [comment]
Ok, so you want to add a link to ask for feedback. Is that right?

I think that Github issues are more transparent and easier to manage for everybody. Is it ok for you?

**Comment by GuillaumeAmat** [comment]
The repository moved to https://gitlab.com/mapcontrib/mapcontrib.next.
