### ISSUE TITLE
After a click on zoom "+" "-" the buton keep focus

### ISSUE THREAD

**Issue by frodrigo** [mapcontrib/mapcontrib.next#18]
Firefox
![image](https://user-images.githubusercontent.com/1785486/39493965-fb89d29a-4d94-11e8-9dd0-a0831c1924a4.png)

Chromium
![image](https://user-images.githubusercontent.com/1785486/39493979-0acf7d54-4d95-11e8-8167-4b21f6be2d45.png)

**Comment by GuillaumeAmat** [comment]
That's normal, it is the common and accessible way to handle focus. Furthermore, I don't see any advantage to modify that behavior.
