### ISSUE TITLE
Add Osmose layers support

### ISSUE THREAD

**Issue by GuillaumeAmat** [mapcontrib/mapcontrib.next#2]

**Comment by vinber** [comment]
+100 :)

**Comment by frodrigo** [comment]
I'm working on switching Osmose to npm + wepback. Now JS code of Osmose is in modules.
Work still in progress https://github.com/frodrigo/osmose-backend/tree/dev

**Comment by GuillaumeAmat** [comment]
Oh, I was about creating two new modules today. A requester and a leaflet layer plugin. I will look at your work first.

What is missing on your side?

**Comment by frodrigo** [comment]
The layer is this one :
https://github.com/frodrigo/osmose-frontend/blob/dev/static/map/Osmose.Marker.js

Main issues:
- Previously I used two versions of "geobug" 1.0.1 and 3.0.0
- When I update npm to new version (mainly leaflet), is no more working

**Comment by GuillaumeAmat** [comment]
I'm afraid your code is too coupled to the Osmose front-end. So I started a new project, [Osmose Request](https://github.com/GuillaumeAmat/osmose-request), to have an agnostic javascript client to talk to the Osmose API.

The work is ongoing and it will be ready soon, at least for the read part.

When it will be, I will start another project to provide Leaflet layers from Osmose requests.

**Comment by GuillaumeAmat** [comment]
FYI, a new project has been started here: https://github.com/GuillaumeAmat/leaflet-nectarivore 🚀
