### ISSUE TITLE
TypeError: helpers_requests__.b.request is null

### ISSUE THREAD

**Issue by frodrigo** [mapcontrib/mapcontrib.next#25]
```
TypeError: __WEBPACK_IMPORTED_MODULE_4_helpers_requests__.b.request is null
OsmoseSidebar/_this.submitCorrection
src/components/edition/OsmoseSidebar.jsx:33

  30 | const original = this.state.error.elems[0];
  31 | const elemId = `${original.type}/${original.id}`;
  32 | 
> 33 | const changesetIdP = osm.request.createChangeset(
  34 |   buildChangesetCreatedBy(),
  35 |   buildChangesetComment(this.props.themePath)
  36 | );
```

Maybe linked with this from the console:
```
Could not authenticate user
```

How to reproduce:
- with osmose layer for editing tag
- click on marker
- click on tags block in the right panel
- click "Valider" on the modal

**Comment by iOiurson** [comment]
I believe this is indeed linked to the fact that we do not manage non-authenticated user yet.

When a solid authentication system is up, the non-authenticated user should be displayed the authentication window when trying to submit a modification.
