### ISSUE TITLE
Eject from Create-React-App ?

### ISSUE THREAD

**Issue by iOiurson** [mapcontrib/mapcontrib.next#26]
I'm starting to feel pissed by the blind project configuration set up by this tool...

**Comment by GuillaumeAmat** [comment]
I was pissed too in the early usage of `create-react-app`, but to be fair, I'm always pissed when I change my workflow and I feel lost.

In the end, I always found a proper solution to my use cases and it saved me a lot of time in projects maintenance (plural).

What are your issues @iOiurson? Maybe we can find a solution to it? If not we will eject the project from `create-react-app` but I really would like not to do it.

**Comment by iOiurson** [comment]
#27 pb was part of it, but it's more a general feeling, that i don't have as much control on the project, too maby things are hidden behing `create-react-app`, and i don't like that (even if it's supposed to be for our own good).

Not everything is annoying (i like how the console is displayed on test runs and file watches), but still.

Anyway, this issue is tagged as "question", so it's still an open matter to discuss.
