### ISSUE TITLE
Migrate to a monorepo using Lerna

### ISSUE THREAD

**Issue by GuillaumeAmat** [mapcontrib/mapcontrib.next#30]
In order to host the server code and the client code at the same place, to share some components, etc.

What do you think about that @iOiurson?

**Comment by GuillaumeAmat** [comment]
The structure could be like that:

```
mapcontrib.next
├── lerna.json
├── package.json
└── packages
    ├── mapcontrib-server
    └── mapcontrib-web
```

**Comment by iOiurson** [comment]
Both projects in the same repo seems like an excellent idea.
I have absolutely no preference on how to do it, never heard of Lerna.

Feel free to start working on the matter.

**Comment by GuillaumeAmat** [comment]
Great :)

**Comment by GuillaumeAmat** [comment]
Perhaps Lerna is not needed after all. Just some folders and a `Makefile` to have proper commands and we're done.
