### ISSUE TITLE
OsmoseSidebar error when no original is present

### ISSUE THREAD

**Issue by iOiurson** [mapcontrib/mapcontrib.next#34]
https://next.mapcontrib.xyz/t/cl7syt/MapContrib/edition/osmose/26022333

![osmose-ecole](https://user-images.githubusercontent.com/8417814/40319591-f775f0aa-5d28-11e8-8186-d1623bc23a09.png)

**Comment by GuillaumeAmat** [comment]
The provided link works now. Is the issue fixed?

**Comment by GuillaumeAmat** [comment]
The repository moved to https://gitlab.com/mapcontrib/mapcontrib.next.
