### ISSUE TITLE
Layout is broken

### ISSUE THREAD

**Issue by iOiurson** [mapcontrib/mapcontrib.next#37]
We do not have access to Toolbars and Sidebars anymore.
I think this is a regression from the Lerna integration, but i'm not 100% sure.

**Comment by GuillaumeAmat** [comment]
Crap... I will look at it when possible

**Comment by GuillaumeAmat** [comment]
@iOiurson I can't reproduce your issue. I'm on develop on both sides and with or without `npm link`...

**Comment by GuillaumeAmat** [comment]
Feel free to reopen if you still have that issue ;)
