### ISSUE TITLE
Show location URL by default, but allow manager to switch that off

### ISSUE THREAD

**Issue by joostschouppe** [mapcontrib/mapcontrib.next#5]
In Mapcontrib, you can generate a link for the current position. But many users expect to be able to just copy the URL of the current view and the share link option is a bit hidden. 
So suggested solution:
- by default, always show the position in the URL
- if there is no position in the URL, show the location the manager defined
- the manager can switch of "show position in URL" in the instance settings

Related to [this old issue](https://github.com/mapcontrib/mapcontrib/issues/273)

**Comment by GuillaumeAmat** [comment]
The repository moved to https://gitlab.com/mapcontrib/mapcontrib.next.
