### ISSUE TITLE
Allow adding other background maps

### ISSUE THREAD

**Issue by joostschouppe** [mapcontrib/mapcontrib.next#6]
At this moment, you can choose some pre-defined background maps. Sometimes, you have better backgrounds available. Please allow the manager to add these (by pasting the URL of a TMS/WMTS source somewhere).

Related to [this issue](https://github.com/mapcontrib/mapcontrib/issues/264) from the previous version.

**Comment by GuillaumeAmat** [comment]
The repository moved to https://gitlab.com/mapcontrib/mapcontrib.next.

**Comment by joostschouppe** [comment]
Doing this would avoid needing an issues for things like [this](https://github.com/mapcontrib/mapcontrib/issues/345)
