### ISSUE TITLE
Can't get the project running

### ISSUE THREAD

**Issue by iOiurson** [mapcontrib/mapcontrib.next#7]
Hi there !

I wanted to start working on this, but I can't get to make it work properly...

`npm run start` returns `Compiled successfully!` but `localhost:3000` displays a grayish empty page, with nothing in the console.

Am I missing something ?

**Comment by iOiurson** [comment]
The App renders, but doesn't render deeper than the `StyledCanvas` component containing all the routes.

<img width="1058" alt="capture d ecran 2018-03-12 a 11 25 54" src="https://user-images.githubusercontent.com/8417814/37278534-57b6e88e-25e8-11e8-9587-563851da2c95.png">

**Comment by GuillaumeAmat** [comment]
Hi!

Did you try http://localhost:3000/t/sqfsdg/MapContrib ?

**Comment by iOiurson** [comment]
What does this url mean ?
This should be explained in the ReadMe.

This url kind of "works".
I get the following screen, and from I could see, the `Toolbar` component seems ok. Any clue ?

<img width="1678" alt="capture d ecran 2018-03-12 a 19 25 31" src="https://user-images.githubusercontent.com/8417814/37302284-5daa3884-262b-11e8-82e4-e25fdcb63f99.png">

**Comment by GuillaumeAmat** [comment]
It is meant to be the url of a theme.

Did you `npm link osm-ui-react`? If not, do it and restart `npm run watch`

**Comment by iOiurson** [comment]
Ok, that worked.
We will have to explain me the trick though.

**Comment by GuillaumeAmat** [comment]
MC Next is based on OSM UI and it uses some components that are not published yet. So you have to link your local copy of OSM UI to have access to those components.
