### ISSUE TITLE
Migrate store management to Rematch ?

### ISSUE THREAD

**Issue by iOiurson** [mapcontrib/mapcontrib.next#8]
I just heard about this [Rematch](https://rematch.gitbooks.io/rematch/#getting-started) lib that provides an (serious) alternative to Redux boilerplate.

Maybe should we look into it and decide if it's worth migrating now, before we get too many functionalities.

**Comment by GuillaumeAmat** [comment]
Great idea!

**Comment by iOiurson** [comment]
I have looked into it a little bit more, and I'm not sure we need to implement this now.
It seems pretty solid, but the Promise management is unclear (and I like Promises a lot).

I'd rather stick to classic Redux for now.
